name: wlai
channels:
  - conda-forge
dependencies:
- python=3.7
- pandas
- scikit-learn
- matplotlib
- notebook
- jupyterlab
- git
- dill
- pip
- imbalanced-learn
- pip:
    - tensorflow
    - keras

